### ISSUE TITLE
Spyglass hide blocks of VanillaX

### ISSUE THREAD

**Issue by MrBlasyMSK** [ItsRealNise/Spyglass#3]
https://github.com/CLADevs/VanillaX/issues/167

**Comment by ItsRealNise** [comment]
Okay i update it

**Comment by MrBlasyMSK** [comment]
> Okay i update it

Thx <3

**Comment by SayaAEP** [comment]
VanillaX good plguins

**Comment by ItsRealNise** [comment]
> > Okay i update it
> 
> Thx <3

Review 1.0.2 fix or not
