### ISSUE TITLE
Spyglass inv creative gone 1.0.1

### ISSUE THREAD

**Issue by SayaAEP** [ItsRealNise/Spyglass#4]
![image](https://user-images.githubusercontent.com/91467886/162864310-0668742c-dae8-4f47-8aec-e425a56ab1e1.png)
Spyglass should be located in creative inventory. when i restart spyglass is in inv create when it restarts again and it's gone.

**Comment by SayaAEP** [comment]
> ![image](https://user-images.githubusercontent.com/91467886/162864310-0668742c-dae8-4f47-8aec-e425a56ab1e1.png) Spyglass should be located in creative inventory. when i restart spyglass is in inv create when it restarts again and it's gone.

`maybe this bug is only on me or on someone else's server too`

**Comment by ItsRealNise** [comment]
waiting for me updating it

**Comment by SayaAEP** [comment]
> waiting for me updating it

ok

**Comment by SayaAEP** [comment]
> waiting for me updating it

baru tau lu org indo

**Comment by ItsRealNise** [comment]
Fix at ver 1.0.2
